# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{serial_interface}
  s.version = "0.3.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Levin Alexander"]
  s.date = %q{2010-01-15}
  s.description = %q{serial_interface intends to be a small library that makes it easy
                         to define packet based protocols over a serial link (RS232) in a
                         declarative fashion.}
  s.email = %q{mail@levinalex.net}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "History.txt",
     "Rakefile",
     "lib/protocol/rca2006.rb",
     "lib/serial_interface.rb",
     "lib/serial_packet.rb",
     "serial_interface.gemspec",
     "test/test_serial_interface.rb",
     "test/test_serial_io.rb",
     "test/test_serial_packets.rb"
  ]
  s.homepage = %q{http://github.com/levinalex/serial_interface}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{abstracts protocols on a serial link}
  s.test_files = [
    "test/helper.rb",
     "test/test_serial_interface.rb",
     "test/test_serial_io.rb",
     "test/test_serial_packets.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<traits>, [">= 0"])
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    else
      s.add_dependency(%q<traits>, [">= 0"])
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    end
  else
    s.add_dependency(%q<traits>, [">= 0"])
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
  end
end

